#!/bin/bash
#SBATCH -J mbl
#SBATCH -o mbl.o%j       
#SBATCH -n 64
#SBATCH -p normal     # queue (partition) -- normal, development, etc.                                                                                               
#SBATCH -t 00:10:00    
#SBATCH --mail-user=phydonglin@gmail.com                                                                                                                             
#SBATCH --mail-type=begin  # email me when the job starts                                                                                                            
#SBATCH --mail-type=end    # email me when the job finishes                                                                                                        
 
ibrun ./mbl

